version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/finhackers
      - SESSION_SECRET=${SESSION_SECRET:-default_session_secret_change_in_production}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=finhackers
      - PGHOST=db
      - PGPORT=5432
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - finhackers-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=finhackers
    ports:
      - "5432:5432"
    networks:
      - finhackers-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  finhackers-network:
    driver: bridge

volumes:
  postgres_data: